# Cloud Build configuration for deploying Study Partner application
# This file deploys both the FastAPI backend and Next.js frontend to Cloud Run

# Build steps will run in sequence
steps:
  # ==================== BACKEND (FastAPI) ====================
  # Build the FastAPI Docker image
  - name: gcr.io/cloud-builders/docker
    id: build-fastapi
    args:
      - build
      - '--no-cache'
      - '-f'
      - fastapi/Dockerfile
      - '--tag'
      - 'gcr.io/$PROJECT_ID/${_FASTAPI_SERVICE}:$SHORT_SHA'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/${_FASTAPI_SERVICE}:latest'
      - fastapi
    waitFor: ['-']  # Start immediately

  # Push the FastAPI image to Container Registry
  - name: gcr.io/cloud-builders/docker
    id: push-fastapi
    args:
      - push
      - 'gcr.io/$PROJECT_ID/${_FASTAPI_SERVICE}:$SHORT_SHA'
    waitFor: ['build-fastapi']

  # Deploy FastAPI to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-fastapi
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_FASTAPI_SERVICE}
      - '--image=gcr.io/$PROJECT_ID/${_FASTAPI_SERVICE}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--set-env-vars=FRONTEND_URL=${_FRONTEND_URL},DATABASE_URL=${_DATABASE_URL},OPENAI_API_KEY=${_OPENAI_API_KEY},JWT_SECRET=${_JWT_SECRET},GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GOOGLE_REDIRECT_URI=${_GOOGLE_REDIRECT_URI}'
      - '--labels=managed-by=cloudbuild,commit-sha=$SHORT_SHA,service=backend'
      - '--quiet'
    waitFor: ['push-fastapi']

  # ==================== FRONTEND (Next.js) ====================
  # Build the Next.js Docker image
  - name: gcr.io/cloud-builders/docker
    id: build-nextjs
    args:
      - build
      - '--no-cache'
      - '-f'
      - nextjs/Dockerfile
      - '--build-arg'
      - 'API_URL=${_API_URL}'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/${_NEXTJS_SERVICE}:$SHORT_SHA'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/${_NEXTJS_SERVICE}:latest'
      - nextjs
    waitFor: ['-']  # Can start in parallel with backend

  # Push the Next.js image to Container Registry
  - name: gcr.io/cloud-builders/docker
    id: push-nextjs
    args:
      - push
      - 'gcr.io/$PROJECT_ID/${_NEXTJS_SERVICE}:$SHORT_SHA'
    waitFor: ['build-nextjs']

  # Deploy Next.js to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-nextjs
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_NEXTJS_SERVICE}
      - '--image=gcr.io/$PROJECT_ID/${_NEXTJS_SERVICE}:$SHORT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'  # Match the port in Next.js Dockerfile
      - '--labels=managed-by=cloudbuild,commit-sha=$SHORT_SHA,service=frontend'
      - '--quiet'
    waitFor: ['push-nextjs']

# List of images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/${_FASTAPI_SERVICE}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_FASTAPI_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_NEXTJS_SERVICE}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_NEXTJS_SERVICE}:latest'

# Default substitution values
# These can be overridden when triggering the build
substitutions:
  _REGION: asia-southeast1  # Changed to a region that might be closer to you
  _FASTAPI_SERVICE: study-partner-api
  _NEXTJS_SERVICE: study-partner-web
  _API_URL: https://${_FASTAPI_SERVICE}-${PROJECT_ID}.a.run.app  # Will be replaced after first deployment
  _FRONTEND_URL: https://${_NEXTJS_SERVICE}-${PROJECT_ID}.a.run.app  # Will be replaced after first deployment
  _DATABASE_URL: ''  # Set this in Cloud Build variables
  _OPENAI_API_KEY: ''  # Set this in Cloud Build variables
  _JWT_SECRET: ''  # Generate a secure random string and set in Cloud Build variables
  _GOOGLE_CLIENT_ID: ''  # Set up OAuth in Google Cloud Console and add here
  _GOOGLE_CLIENT_SECRET: ''  # Set in Cloud Build variables
  _GOOGLE_REDIRECT_URI: https://${_FASTAPI_SERVICE}-${PROJECT_ID}.a.run.app/api/auth/google/callback

# Additional build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8  # More powerful machine for faster builds
  # Uncomment and set your service account if needed
  # serviceAccount: projects/$PROJECT_ID/serviceAccounts/[SERVICE_ACCOUNT]@$PROJECT_ID.iam.gserviceaccount.com

# Timeout after 20 minutes (default is 10m)
timeout: 1200s

# Tags for the build
# tags:
#   - 'fastapi'
#   - 'nextjs'
#   - 'production'
