steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-f'
      - nextjs/Dockerfile
      - '--build-arg'
      - 'API_URL=${_API_URL}'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - nextjs

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--port=3000'

images:
  - 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}'

substitutions:
  _SERVICE_NAME: study-partner-web
  _REGION: us-central1
  _API_URL: https://YOUR_BACKEND_URL

options:
  logging: CLOUD_LOGGING_ONLY

